add_newline = true

[shell]
disabled = false
zsh_indicator = "ğŸ™"

[memory_usage]
disabled = false
threshold = 50
format = "$symbol via [${ram_pct} | ${ram}]($style)"

[git_branch]
symbol = "ğŸŒ¿ "

[nodejs]
symbol = "ğŸ© "
